### ISSUE TITLE
Example contains two imports of time module.

### ISSUE THREAD

**Issue by drobati** [madisonmay/Tomorrow#14]
In the second example where you added Tomorrow to the first example, you had a second import of time after the ifmain. Is this necessary?

I didn't see any explanation of why it was added.

**Comment by madisonmay** [comment]
Nope, not at all.  I'll fix it promptly, thanks for the report!

**Comment by madisonmay** [comment]
Resolved. Thanks again!

**Comment by drobati** [comment]
No problem.
