### ISSUE TITLE
cannot import name threads

### ISSUE THREAD

**Issue by kakaok** [madisonmay/Tomorrow#15]
# coding=utf-8

import time
import requests
from tomorrow import threads
urls=[
      'http://www.baidu.com',
      'http://www.sina.com',
      'http://www.ifeng.com',
      'http://www.13393.com',
      'http://www.bing.com'
      ]
@threads(5)
def dowload(url):
    return requests.get(url)

if **name** == '**main**':
    start=time.time()
    responses=[dowload(url) for url in urls]
    html=[response.text for response in responses]
    end=time.time()
    print 'Time:%f seconds' %(end-start)

Traceback (most recent call last):
  File "/home/kaka/workspace/PythonProject/Https/PC/tomorrowdemo.py", line 5, in <module>
    from tomorrow import threads
  File "/home/kaka/workspace/PythonProject/Https/PC/tomorrow.py", line 4, in <module>
ImportError: cannot import name threads

**Comment by madisonmay** [comment]
Could your report the results of `pip freeze | grep tomorrow`?

My guess is you're on an older version.

**Comment by madisonmay** [comment]
@kakaok

**Comment by madisonmay** [comment]
Closing since there hasn't been a response in a while.

**Comment by kakaok** [comment]
thanks

**Comment by madisonmay** [comment]
no problem!
