### ISSUE TITLE
run test.py error

### ISSUE THREAD

**Issue by kcbsbo** [madisonmay/Tomorrow#19]
1. does test.py only support python2? Runtime error if I use python3 interpreter cuz print function without parentheses
2. Runtime error also

Error
Traceback (most recent call last):
  File "D:\project\Tomorrow\tests\test.py", line 95, in test_future_function
    assert true()
TypeError: 'Tomorrow' object is not callable

<tomorrow.tomorrow.Tomorrow object at 0x029885D0>
<tomorrow.tomorrow.Tomorrow object at 0x02988730>

Failure
Traceback (most recent call last):
  File "D:\project\Tomorrow\tests\test.py", line 68, in test_shared_executor
    assert (N \* DELAY) < (end - start) < (2 \* N \* DELAY)
AssertionError

<tomorrow.tomorrow.Tomorrow object at 0x02988810>
<tomorrow.tomorrow.Tomorrow object at 0x02988930>

**Comment by madisonmay** [comment]
Only python2 is supported.  README has been updated to reflect this.  Sorry!
