### ISSUE TITLE
This code does not work on python3

### ISSUE THREAD

**Issue by brammittendorff** [madisonmay/Tomorrow#7]
✔ ~/projects[master ↓·2|…2] 
10:25 $ python3 get_urls.py 
Traceback (most recent call last):
  File "get_urls.py", line 4, in <module>
    from tomorrow import threads
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tomorrow/**init**.py", line 1, in <module>
    from tomorrow import threads
ImportError: cannot import name 'threads'
✔ ~/projects[master ↓·2|…2] 
10:25 $ python get_urls.py 
Time: 4.356341 seconds

**Comment by adrian17** [comment]
For `from tomorrow import threads` to work, it probably would have to be contained in a single file (instead of a directory with `__init__`).

...or just change `__init__` to `from tomorrow.tomorrow import threads`

By the way, tests also use Python2's `print`.

**Comment by madisonmay** [comment]
So oddly enough, it's non-trivial to port this code to Python 3.  This is because I rely on old-style Python class behavior to ensure calls to `__method__`'s are intercepted.  See https://docs.python.org/2/reference/datamodel.html#new-style-and-classic-classes for details.

**Comment by Slater-Victoroff** [comment]
2.7 is love, 2.7 is life.

**Comment by brammittendorff** [comment]
Allright i will close this

**Comment by madisonmay** [comment]
Sorry about that!
