### ISSUE TITLE
Clarify which versions of Python are supported

### ISSUE THREAD

**Issue by cclauss** [madisonmay/Tomorrow#9]
My sense is that this will work in Python 3.2 and later but not in Python 2.  Is that correct?  It would be useful if that was clearly stated in both the readme and in the pypi record.

**Comment by douglasmiranda** [comment]
I can confirm It works on python2.7.

@cclauss futures for python 2 o/ :D https://github.com/agronholm/pythonfutures

**Comment by chadgh** [comment]
I can confirm that it doesn't pip install successfully in python 3.3. :(

**Comment by madisonmay** [comment]
Yup, I need to document that in the README -- it is not intended to work for python3 because it takes advantage of python2 specific features (namely old-style Python classes) to make the magic work. Sorry @chadgh and @cclauss

**Comment by madisonmay** [comment]
Added a few more characters to the README to specify Python 2.7+.  Hopefully that's sufficient.
Thanks for opening this issue @cclaus!
